### ISSUE TITLE
Use AWS profile / env variables.

### ISSUE THREAD

**Issue by davidnewhall** [deb-s3/deb-s3#10]
I'm not real sure what's going on here, but it seems like this tool doesn't use the AWS profile env variables correctly. See below.
```
$ AWS_DEFAULT_PROFILE=my-s3-artifacts AWS_DEFAULT_REGION=us-west-2 AWS_PROFILE=my-s3-artifacts deb-s3 upload --bucket my-deb-s3 ./nrdc-debian.deb
>> Retrieving existing manifests
>> Examining package file nrdc-debian.deb
>> Uploading packages and new manifests to S3
   -- Transferring pool/stable/n/nr/nrdc-debian.deb
Traceback (most recent call last):
        27: from /usr/local/bin/deb-s3:23:in `<main>'
        26: from /usr/local/bin/deb-s3:23:in `load'
        25: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/bin/deb-s3:9:in `<top (required)>'
        24: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        23: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        22: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        21: from /Library/Ruby/Gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        20: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/cli.rb:248:in `upload'
        19: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/cli.rb:248:in `each_value'
        18: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/cli.rb:250:in `block in upload'
        17: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/manifest.rb:107:in `write_to_s3'
        16: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/manifest.rb:107:in `each'
        15: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/manifest.rb:109:in `block in write_to_s3'
        14: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/utils.rb:103:in `s3_store'
        13: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/utils.rb:103:in `open'
        12: from /Library/Ruby/Gems/2.6.0/gems/deb-s3-0.11.2/lib/deb/s3/utils.rb:105:in `block in s3_store'
        11: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/client.rb:11267:in `put_object'
        10: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/seahorse/client/request.rb:72:in `send_request'
         9: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
         8: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
         7: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
         6: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
         5: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
         4: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
         3: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
         2: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/plugins/dualstack.rb:36:in `call'
         1: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
/Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.113.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': Access Denied (Aws::S3::Errors::AccessDenied)
```
---
Same credentials work fine with `aws s3 cp`:
```
$ AWS_DEFAULT_PROFILE=my-s3-artifacts AWS_DEFAULT_REGION=us-west-2 AWS_PROFILE=my-s3-artifacts aws s3 cp nrdc-debian.deb s3://my-deb-s3/
upload: ./nrdc-debian.deb to s3://my-deb-s3/nrdc-debian.deb
```

**Comment by daniel-aicradle** [comment]
I have to second the workaround suggested by @9to6 
I believe the core issue is that the visibility is defaulting to public so it is trying to make that package publicly available which conflicts with bucket s3 permissions. So I think less an issue than easy to misunderstand/miss documentation. I think defaulting to private visibility is probably a better choice from a security perspective.
