### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by DeboBurro** [deb-s3/deb-s3#35]
having issue process the package info when uploading to s3 apt repository
Might related to this [issue](https://github.com/krobertson/deb-s3/issues/34)
```
>> Examining package file cron_3.0pl1-136ubuntu1_amd64.deb
/var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/package.rb:291:in `block (2 levels) in parse_control': invalid byte sequence in US-ASCII (ArgumentError)
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/package.rb:290:in `each_line'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/package.rb:290:in `block in parse_control'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/package.rb:289:in `tap'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/package.rb:289:in `parse_control'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/package.rb:232:in `extract_info'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/package.rb:46:in `parse_file'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/cli.rb:185:in `block in upload'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/cli.rb:183:in `each'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/lib/deb/s3/cli.rb:183:in `upload'
	from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /var/lib/gems/2.7.0/gems/deb-s3-0.11.7/bin/deb-s3:9:in `<top (required)>'
	from /usr/local/bin/deb-s3:23:in `load'
	from /usr/local/bin/deb-s3:23:in `<main>'
```
potential cause is the Maintainer name has special charaters
```
username@hostname:~/$ apt-cache show cron
Package: cron
Architecture: amd64
Version: 3.0pl1-136ubuntu1
Multi-Arch: foreign
Priority: standard
Section: admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Javier Fernández-Sanguino Peña <jfs@debian.org>
```

**Comment by morph027** [comment]
Can you try `LC_ALL=C.UTF-8 deb-s3 <your-command>` ?

**Comment by DeboBurro** [comment]
@morph027 Thank you so much. All my local debians are able to be uploaded to S3 bucket.
