### ISSUE TITLE
deb-s3 and Google Buckets / Google Cloud Storage

### ISSUE THREAD

**Issue by pavel-odintsov** [deb-s3/deb-s3#45]
Hello!

Thank you for great software! 

I faced issue with Google S3 protocol.

I'm trying to upload test 3.8Mb deb file to Google Bucket:
```
ls -alh ~/Downloads/steam_latest.deb 
-rw-rw-r-- 1 pavel pavel 3.8M Jun  8 20:42 /home/pavel/Downloads/steam_latest.deb
```

Sadly it fails with this error:
```
 bin/deb-s3 upload --access-key-id=xxxx --secret-access-key=xxxx   --bucket debs3testrepo   ~/Downloads/steam_latest.deb --endpoint=https://storage.googleapis.com 
 
>> Retrieving existing manifests
>> Examining package file steam_latest.deb
>> Uploading packages and new manifests to S3
   -- Transferring dists/stable/main/binary-amd64/Packages
/var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': Invalid argument. (Aws::S3::Errors::InvalidArgument)
	from /var/lib/gems/3.2.0/gems/aws-sdk-s3-1.152.2/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-s3-1.152.2/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-s3-1.152.2/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/aws-sdk-core/plugins/invocation_id.rb:16:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	from /var/lib/gems/3.2.0/gems/aws-sdk-core-3.197.0/lib/seahorse/client/request.rb:72:in `send_request'
	from /var/lib/gems/3.2.0/gems/aws-sdk-s3-1.152.2/lib/aws-sdk-s3/client.rb:15616:in `put_object'
	from /home/pavel/repo/deb-s3/lib/deb/s3/utils.rb:106:in `block in s3_store'
	from /home/pavel/repo/deb-s3/lib/deb/s3/utils.rb:104:in `open'
	from /home/pavel/repo/deb-s3/lib/deb/s3/utils.rb:104:in `s3_store'
	from /home/pavel/repo/deb-s3/lib/deb/s3/manifest.rb:119:in `write_to_s3'
	from /home/pavel/repo/deb-s3/lib/deb/s3/cli.rb:245:in `block in upload'
	from /home/pavel/repo/deb-s3/lib/deb/s3/cli.rb:243:in `each_value'
	from /home/pavel/repo/deb-s3/lib/deb/s3/cli.rb:243:in `upload'
	from /var/lib/gems/3.2.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /var/lib/gems/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/3.2.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /var/lib/gems/3.2.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	from bin/deb-s3:9:in `<main>'
```

In case of s3cmd I have to use flag --disable-multipart to make it work with Google Buckets.

It is possible to add some flag for deb-s3 for it?

Thank you!

**Comment by pavel-odintsov** [comment]
I created PR for it: https://github.com/deb-s3/deb-s3/pull/60
